### ISSUE TITLE
App screenshots for website

### ISSUE THREAD

**Issue by MZO9400** [GAPP-Intelligence/gappblockssite#65]
Screenshots required for:
- Homepage
- An order being tracked
- Received push notifications

**Comment by Afrasyabafzal** [comment]
Homepage:
![image](https://user-images.githubusercontent.com/73391352/187251339-fee8aaf4-6cc6-4001-a5f4-60ba58d11e06.png)

Order Accepted:
![image](https://user-images.githubusercontent.com/73391352/187253839-74f681e9-30e0-448c-ac30-82be300678d6.png)

**Comment by Afrasyabafzal** [comment]
![image](https://user-images.githubusercontent.com/73391352/187256191-39a0be64-f2be-4870-9ea6-a57abc02ceb3.png)
![image](https://user-images.githubusercontent.com/73391352/187256553-981c8e21-07cc-4926-8874-ad3b4f7abf3b.png)

**Comment by Afrasyabafzal** [comment]
Homepage:
![screenshot](https://user-images.githubusercontent.com/73391352/187265499-c5514cfe-dd4d-4ba1-af5e-b7a53f99b83e.png)
Order tracking:
![screenshot](https://user-images.githubusercontent.com/73391352/187266743-aac9586f-52e2-4e5a-a0f4-1b348891cb74.png)

**Comment by Afrasyabafzal** [comment]
GAPP Finder:
HomeScreen:
![screenshot](https://user-images.githubusercontent.com/73391352/187464004-37be5886-25a1-4480-ad87-76c83e01c009.png)

Order Tracking:
![screenshot](https://user-images.githubusercontent.com/73391352/187464063-d70cc38e-f749-4145-b99b-36f1e06c34d1.png)

Notification:
![screenshot](https://user-images.githubusercontent.com/73391352/187463951-191f61d8-86c6-4680-925e-44b19a3c1cfc.png)
