### ISSUE TITLE
Screenshots for Finder app

### ISSUE THREAD

**Issue by MZO9400** [GAPP-Intelligence/gappblockssite#97]
Finder:

- Homepage
- Earnings page
- Screenshot of an order

Make sure the currency is US Dollar "$"

**Comment by Afrasyabafzal** [comment]
Earnings:
![screenshot](https://user-images.githubusercontent.com/73391352/187708300-82a14e74-ac5f-4aea-9a33-7ca28af398ab.png)

Order:
![screenshot](https://user-images.githubusercontent.com/73391352/187708828-b5d25662-beee-4606-a02f-8af5e7324753.png)

![screenshot](https://user-images.githubusercontent.com/73391352/187709436-e7ebeb06-03cf-4b41-871f-6f5643753800.png)

![screenshot](https://user-images.githubusercontent.com/73391352/187709677-f427b951-d3a7-4eb1-b3b0-5eaaa0cc6e4a.png)

Homepage:
![screenshot](https://user-images.githubusercontent.com/73391352/187710421-b60435da-0927-4541-991c-2e0d56329510.png)

**Comment by MZO9400** [comment]
@Afrasyabafzal update the screenshots with USA address

**Comment by Afrasyabafzal** [comment]
Order:
![screenshot](https://user-images.githubusercontent.com/73391352/187731506-1c24002d-5af7-41d5-a058-d1b2e88009d6.png)

![screenshot](https://user-images.githubusercontent.com/73391352/187731702-78164d06-3ec8-4f52-97b0-762fab03b6bd.png)

![screenshot](https://user-images.githubusercontent.com/73391352/187732089-d2ee23b6-9677-4896-80bc-da1b7801b691.png)

Earnings:
![screenshot](https://user-images.githubusercontent.com/73391352/187732311-59fdc399-05a5-44bd-8cd6-e49c25792d75.png)

Homepage:
![screenshot](https://user-images.githubusercontent.com/73391352/187732431-b43926ae-9eb0-40c3-a28d-c9652ffe984f.png)

**Comment by Afrasyabafzal** [comment]
![screenshot](https://user-images.githubusercontent.com/73391352/187735256-be545d0b-b01a-4928-bab5-ad8a287d53af.png)

![screenshot](https://user-images.githubusercontent.com/73391352/187735356-688c485b-9680-42a2-bcd7-e2f8a7cbc476.png)
